name: Deploy to Lightsail

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  workflow_dispatch:  # Allow manual trigger from the GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull repo changes and restart FastAPI and NGINX on Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }} << EOF
          cd ~/fountainai-fastapi-proxy
          git pull origin main
          sudo systemctl restart fastapi
          sudo systemctl restart nginx
          sudo systemctl status fastapi
          sudo systemctl status nginx
        EOF
