name: Run FastAPI Tests

on:
  push:
    branches:
      - refactor-fastapi
  pull_request:
    branches:
      - refactor-fastapi

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest and store logs in repository
      run: |
        mkdir -p test_logs/${{ matrix.python-version }}
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        pytest tests/ | tee test_logs/${{ matrix.python-version }}/test_log_${{ matrix.python-version }}_$TIMESTAMP.txt
        git config --global user.email "mail@benedikt-eickhoff.de"
        git config --global user.name "Benedikt Eickhoff"
        git add test_logs/${{ matrix.python-version }}/test_log_${{ matrix.python-version }}_$TIMESTAMP.txt
        git commit -m "Adding test logs for Python ${{ matrix.python-version }} run on $TIMESTAMP"
        git push origin refactor-fastapi
