name: Run FastAPI Tests

on:
  push:
    branches:
      - refactor-fastapi
  pull_request:
    branches:
      - refactor-fastapi

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Updated to v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest and save output to logs
      run: |
        export TEST_LOG_DIR=logs
        mkdir -p $TEST_LOG_DIR
        pytest tests/ | tee $TEST_LOG_DIR/test_log.txt
    
    - name: Upload test results
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: test-logs
        path: logs/test_log.txt  # Directly referencing logs directory
